// GENERATED by tools/make-art.py — do not edit by hand.
// Re-run: .venv/bin/python tools/make-art.py

export const images = {
  'court-action': require('../assets/img/cut/court-action.png'),
  'racket-arc': require('../assets/img/cut/racket-arc.png'),
  'racket-blade': require('../assets/img/cut/racket-blade.png'),
  'racket-drift': require('../assets/img/cut/racket-drift.png'),
  'racket-kinetic': require('../assets/img/cut/racket-kinetic.png'),
  'racket-pair': require('../assets/img/cut/racket-pair.png'),
  'racket-storm': require('../assets/img/cut/racket-storm.png'),
  'shuttle-feather': require('../assets/img/cut/shuttle-feather.png'),
  'shuttle-tube': require('../assets/img/cut/shuttle-tube.png'),
} as const;

export type ImageKey = keyof typeof images;
