"""Cut every product photograph out of its studio background and write the
manifest the app imports.

Runs over `assets/img/*.jpg` automatically — drop a new photo in, re-run, done.

Why keying rather than the elliptical falloff the sushi app uses: a racket is
long, thin and usually diagonal in frame. An ellipse centred on the subject
either clips the handle or grows until it swallows the backdrop. Product shots
are lit against a plain ground, so distance from the sampled backdrop colour
separates subject from background far more faithfully, and keeps the real
silhouette — which is the whole point of the comps' cut-out look.

Usage:
    python3 -m venv .venv && .venv/bin/pip install numpy pillow
    .venv/bin/python tools/make-art.py

Stop the Metro dev server first: it watches `assets/` and will read a PNG
mid-write, then cache `Error: Empty file` against it until restarted.
"""

import glob
import os

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "img")
CUT = os.path.join(SRC, "cut")
MANIFEST = os.path.join(ROOT, "data", "images.ts")

# The page ground the cut-outs land on. Edge pixels are graded toward this, so
# a photo shot against pure white doesn't leave a bright halo on #F1F1F1.
GROUND = np.array([0xF1, 0xF1, 0xF1], np.float32)

WIDTH = 1000


def smoothstep(a, b, x):
    t = np.clip((x - a) / max(b - a, 1e-6), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def backdrop_colour(px):
    """Median of a border band, which is nearly always backdrop."""
    h, w, _ = px.shape
    band = max(4, min(h, w) // 20)
    edge = np.concatenate(
        [
            px[:band].reshape(-1, 3),
            px[-band:].reshape(-1, 3),
            px[:, :band].reshape(-1, 3),
            px[:, -band:].reshape(-1, 3),
        ]
    )
    return np.median(edge, axis=0)


def despeckle(alpha, radius=3):
    """Morphological open then close, to drop dust and fill pinholes.

    A racket's strings are a lattice of near-backdrop pixels, so keying alone
    leaves the head full of holes. Closing seals them; opening first removes
    the sensor noise that closing would otherwise inflate into blobs.
    """
    im = Image.fromarray((alpha * 255).astype(np.uint8))
    size = radius * 2 + 1
    im = im.filter(ImageFilter.MinFilter(size)).filter(ImageFilter.MaxFilter(size))
    im = im.filter(ImageFilter.MaxFilter(size)).filter(ImageFilter.MinFilter(size))
    return np.asarray(im, np.float32) / 255.0


def cutout(src, dst, feather=0.004, settle=0.85):
    """Key one photograph onto the ground and write a transparent PNG."""
    im = Image.open(src).convert("RGB")
    scale = WIDTH / im.width
    im = im.resize((WIDTH, max(1, round(im.height * scale))), Image.LANCZOS)
    w, h = im.size

    px = np.asarray(im, np.float32) / 255.0
    back = backdrop_colour(px)

    # Distance from the backdrop, normalised against its own spread so the
    # thresholds hold whether the ground is white, grey or faintly tinted.
    dist = np.sqrt(((px - back) ** 2).sum(axis=2) / 3.0)
    lo, hi = np.percentile(dist, 55), np.percentile(dist, 88)
    a = smoothstep(lo, max(hi, lo + 1e-3), dist)

    a = despeckle(a)
    a = np.asarray(
        Image.fromarray((a * 255).astype(np.uint8)).filter(
            ImageFilter.GaussianBlur(w * feather)
        ),
        np.float32,
    ) / 255.0

    # Grade toward the ground as alpha drops. Without this, a white-backdrop
    # photo fades through white and rims the product in a bright halo.
    rgb = np.asarray(im, np.float32)
    mix = (1.0 - a[..., None]) * settle
    rgb = rgb * (1.0 - mix) + GROUND * mix

    out = Image.fromarray(
        np.dstack([rgb.astype(np.uint8), (a * 255).astype(np.uint8)]), "RGBA"
    )

    # Trim the fully transparent margin: screens stretch these into a fixed
    # box, so dead space around the product silently shrinks it.
    box = out.getchannel("A").point(lambda v: 255 if v > 4 else 0).getbbox()
    if box:
        out = out.crop(box)
    out.save(dst, optimize=True)
    return out.size


def main():
    os.makedirs(CUT, exist_ok=True)
    slugs = []

    for src in sorted(glob.glob(os.path.join(SRC, "*.jpg"))):
        slug = os.path.splitext(os.path.basename(src))[0]
        dst = os.path.join(CUT, f"{slug}.png")
        size = cutout(src, dst)
        print(f"cut   {slug:16s} -> {size[0]}x{size[1]}")
        slugs.append(slug)

    # The manifest is generated because React Native's `require` must be a
    # static literal — a new photo would otherwise need a hand-written import
    # before the app could see it.
    lines = [
        "// GENERATED by tools/make-art.py — do not edit by hand.",
        "// Re-run: .venv/bin/python tools/make-art.py",
        "",
        "export const images = {",
    ]
    lines += [f"  '{s}': require('../assets/img/cut/{s}.png')," for s in slugs]
    lines += [
        "} as const;",
        "",
        "export type ImageKey = keyof typeof images;",
        "",
    ]
    with open(MANIFEST, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(MANIFEST, ROOT)} with {len(slugs)} entries")


if __name__ == "__main__":
    main()
