// GENERATED by tools/make-art.py — do not edit by hand.
//
// Every dish photograph, plus the feathered cut-out of it used as a
// detail-screen hero. Re-run the script after adding a photograph.

export const photos = {
  'avocado-maki': require('../assets/img/avocado-maki.jpg'),
  'california-roll': require('../assets/img/california-roll.jpg'),
  'chef-selection': require('../assets/img/chef-selection.jpg'),
  'deluxe-platter': require('../assets/img/deluxe-platter.jpg'),
  'dragon-roll': require('../assets/img/dragon-roll.jpg'),
  'hero-platter': require('../assets/img/hero-platter.jpg'),
  'maki-grid': require('../assets/img/maki-grid.jpg'),
  'omakase-boat': require('../assets/img/omakase-boat.jpg'),
  'philadelphia-roll': require('../assets/img/philadelphia-roll.jpg'),
  'premium-nigiri': require('../assets/img/premium-nigiri.jpg'),
  'rainbow-deluxe': require('../assets/img/rainbow-deluxe.jpg'),
  'rainbow-roll': require('../assets/img/rainbow-roll.jpg'),
  'salmon-aburi': require('../assets/img/salmon-aburi.jpg'),
  'salmon-uramaki': require('../assets/img/salmon-uramaki.jpg'),
  'spicy-tuna-roll': require('../assets/img/spicy-tuna-roll.jpg'),
  'sushi-spread': require('../assets/img/sushi-spread.jpg'),
  'tobiko-roll': require('../assets/img/tobiko-roll.jpg'),
  'unagi-nigiri': require('../assets/img/unagi-nigiri.jpg'),
} as const;

export const cutouts = {
  'avocado-maki': require('../assets/img/cut/avocado-maki.png'),
  'california-roll': require('../assets/img/cut/california-roll.png'),
  'chef-selection': require('../assets/img/cut/chef-selection.png'),
  'deluxe-platter': require('../assets/img/cut/deluxe-platter.png'),
  'dragon-roll': require('../assets/img/cut/dragon-roll.png'),
  'hero-platter': require('../assets/img/cut/hero-platter.png'),
  'maki-grid': require('../assets/img/cut/maki-grid.png'),
  'omakase-boat': require('../assets/img/cut/omakase-boat.png'),
  'philadelphia-roll': require('../assets/img/cut/philadelphia-roll.png'),
  'premium-nigiri': require('../assets/img/cut/premium-nigiri.png'),
  'rainbow-deluxe': require('../assets/img/cut/rainbow-deluxe.png'),
  'rainbow-roll': require('../assets/img/cut/rainbow-roll.png'),
  'salmon-aburi': require('../assets/img/cut/salmon-aburi.png'),
  'salmon-uramaki': require('../assets/img/cut/salmon-uramaki.png'),
  'spicy-tuna-roll': require('../assets/img/cut/spicy-tuna-roll.png'),
  'sushi-spread': require('../assets/img/cut/sushi-spread.png'),
  'tobiko-roll': require('../assets/img/cut/tobiko-roll.png'),
  'unagi-nigiri': require('../assets/img/cut/unagi-nigiri.png'),
} as const;

export type PhotoKey = keyof typeof photos;
